import { Message } from "@/types";

export const demoMessages: Message[] = [
  {
    id: "msg-1",
    role: "user",
    content: "Hello! I need help with my order.",
    type: "text",
    timestamp: "2025-07-12T10:00:00Z",
    status: "sent",
  },
  {
    id: "msg-2",
    role: "bot",
    content: "Sure! Can you provide your order number?",
    type: "text",
    timestamp: "2025-07-12T10:00:02Z",
    status: "received",
  },
  {
    id: "msg-3",
    role: "user",
    content: "Yes, it's ORD123456.",
    type: "text",
    timestamp: "2025-07-12T10:00:05Z",
    status: "sent",
  },
  {
    id: "msg-4",
    role: "bot",
    content: "Got it. Here's the product from your order:",
    type: "image",
    timestamp: "2025-07-12T10:00:08Z",
  },
  {
    id: "msg-5",
    role: "bot",
    content: "Would you like to track your order or speak to an agent?",
    type: "button",
    timestamp: "2025-07-12T10:00:12Z",
  },
  {
    id: "msg-6",
    role: "user",
    content: "Track Order",
    type: "text",
    timestamp: "2025-07-12T10:00:15Z",
    status: "sent",
  },
  {
    id: "msg-7",
    role: "bot",
    content: "Your order is on the way and will arrive by July 15.",
    type: "text",
    timestamp: "2025-07-12T10:00:18Z",
  },
  {
    id: "msg-8",
    role: "bot",
    content: "Need more help? Watch this quick video guide.",
    type: "video",
    timestamp: "2025-07-12T10:00:20Z",
  },
  {
    id: "msg-9",
    role: "bot",
    content: "Download your order invoice below.",
    type: "file",
    timestamp: "2025-07-12T10:00:25Z",
  },
  {
    id: "msg-10",
    role: "bot",
    content: "Recommended for you:",
    type: "card",
    timestamp: "2025-07-12T10:00:30Z",
  },
  {
    id: "msg-20",
    role: "bot",
    content: "Recommended for you:",
    type: "card",
    timestamp: "2025-07-12T10:00:30Z",
  },
  {
    id: "msg-30",
    role: "bot",
    content: "Recommended for you:",
    type: "card",
    timestamp: "2025-07-12T10:00:30Z",
  },
  {
    id: "msg-350",
    role: "bot",
    content: "Recommended for you:",
    type: "card",
    timestamp: "2025-07-12T10:00:30Z",
  },
];
